[program]
name = "Example program"
description = "The description of the program"
epilog = "Goes at the end"

[[arguments]]
name = "input"
type = "string"
help = "input TOML file"

[[arguments]]
name = "--output"
short = "-o"
type = "string"
help = "output file"
default = "cli_args"

[[arguments]]
name = "--lang"
short = "-l"
type = "string"
help = "language for the generated code"
choices = "python,bash"

[[arguments]]
name = "--files"
short = "-f"
type = "string"
multiple = "true"
default = "a.txt b.txt"
help = "pass any number of files"
